### ISSUE TITLE
Disable Default context menu when using CTRL+RMB

### ISSUE THREAD

**Issue by KevinSanders** [choobin/cmis#29] opened 2013-01-21 21:14 UTC
I've just started using this hotkey. Very nice and simple idea. The only thing is the default firefox context menu appears every time I use it (which is annoying on galleries as it blocks the next arrow). Could you block the default context menu from appearing while using CTRL+RMB or allow a custom user shortcut?

I've tried the "customizable-shortcuts" add-on. Although it lists other add-ons, it doesn't list CMIS.

**Comment by choobin** [comment] 2013-01-21 23:14
I have encountered this issue before. After a massive  investigation I was lead to believe that this behaviour was caused by CMIS and other extensions not playing well togeather.

If you have some spare time could you do a test for me? Create a new profile with no extensions installed and install CMIS and see if it still happens. Then progressively install your other extensions until we find the culprit. This should help to address the issue.

**Comment by KevinSanders** [comment] 2013-01-22 03:23
Will do! I'll update this post with my findings.

---

OK, made a different profile called CMIS with "firefox.exe -P". Installed the same version (MD5: DF032F7521D49DA8C9FC688C04B24356). No other add-ons.
- I tried to add paths. Nothing showed up. Just remained blank.
- Tried to import my settings. Still nothing.

That was weird. Deleted that profile and created a new one called "test". Same result.

Back to my "default" profile and it's still working perfectly.

Windows 8 64-bit, Firefox 32-bit 18.0.1
I always have that crappy wndows UAC completely off. 

---

UPDATE (regarding the add-on 'path list' not working with a different profile with NO extra add-ons):
cmis-master_2013-01-19v2 (MD5: DF032F7521D49DA8C9FC688C04B24356) = (latest build) Didn't work
cmis-master_2013-01-19 (MD5: A16A9C5406BA8037630F999F213D49E9) = Didn't work
cmis-master_2013-01-13 (MD5: 1DE95E5E65EA18AE829F150FD0F2C65C) = CTRL+RMB works with no context menu showing, Path list Works, but pre-dates the import/export feature.

**Comment by KevinSanders** [comment] 2013-01-23 00:20
OK, added all my add-ons to a new profile (Used FEBE to back everything up...man that was still a pain due to so many addons...LOL). Added them one-by-one and tested after each restart.

Would you believe the RMB works fine now? The test profile is now my current one. Go figure!

**Comment by choobin** [comment] 2013-01-23 06:17
@KevinSanders

Cheers for everything. 

> Would you believe the RMB works fine now? The test profile is now my current one. Go figure!

Wow. Very frustrating. At least you have a functional set-up!

The following [two lines](https://github.com/choobin/cmis/blob/master/src/bootstrap.js#L341-L343) _should_ prevent the quick save event from creating the context menu.

I think the source of the issue boils down to too many extensions mucking with the context menu. As soon and I get some time I will venture to IRC and a few mailing lists to see if I can find any developers that might understand the issue.

It is really hard to fix this as I can not reproduce the error on-call. It just happens after I install an arbitrary number of extensions. At least it is documented now. Next time it happens on my box I have bring out the big guns.

**Comment by KevinSanders** [comment] 2013-01-23 14:49
No worries. Although I'm using all of the same add-ons, firefox feels a tad lighter.

The only one I was suspecting was this:
https://addons.mozilla.org/en-US/firefox/addon/flash-video-downloader-youtube/
As just after installing it, the context menu showed only the one time. But it hasn't showed since.

What about adding a user definable shortcut? One that uses the LMB instead maybe? There's probably other issues that could arise with that I'm not aware of.

**Comment by KevinSanders** [comment] 2013-01-25 01:25
So far it's still working great. Really handy now that the context menu isn't getting in the way.

One thing though. Can you make it use the same save path as opposed to the "save image as..." action? When I try to save to same directory that I used that for, it keeps opening the "save image as" window (which defeats it's purpose). When CTRL+RMB saving an image to a previously used path, it works as expected.

**Comment by choobin** [comment] 2013-01-26 08:36
> What about adding a user definable shortcut? One that uses the LMB instead maybe? There's probably other issues that could arise with that I'm not aware of.

Providing other shortcut combinations is a great idea [issue/30](https://github.com/choobin/cmis/issues/30).

> One thing though. Can you make it use the same save path as opposed to the "save image as..." action? 

Good spot [issue/31](https://github.com/choobin/cmis/issues/31).

I looks like I will get some time over the weekend to work on CMIS. So stay tuned.

**Comment by choobin** [comment] 2013-01-28 07:45
Updated in [ea301ddab1](https://github.com/choobin/cmis/commit/ea301ddab1d49ce11353ad872830f4871baa7305).

I have a possible solution. I am now calling stopPropagation and preventDefault on the click event as soon as possible. This _should_ prevent FF or any other extensions from mucking with the context menu. I will close this issue for now. However, it starts happening again I will have to reopen it.

**Comment by choobin** [comment] 2013-01-29 13:28
I am re-opening this issue. 

I have received reports that is it still occurring (intermittently) when 

https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/

and

https://addons.mozilla.org/en-US/firefox/addon/flash-video-downloader-youtube/

are installed.

**Comment by KevinSanders** [comment] 2013-02-02 18:39
Flash Video Downloader works fine with CMIS now. I haven't used Video DownloadHelper since I started with this new profile. So that could well be the culprit.

**Comment by choobin** [comment] 2013-02-03 23:37
Thanks for the information. I have been playing around with the extension. I still can not seem to replicate the issue. However, I have encountered it before. I will figure out what is going on at some point.

**Comment by choobin** [comment] 2013-06-14 23:52
@KevinSanders. I have not had any issues with the context menu firing on quick save for some time now. I am going to close this issue. If it starts occurring again I will start tinkering around again. 

Cheers,

Chris

**Closed as completed by choobin** 2013-06-14 23:52 UTC
Labels: bug
