### ISSUE TITLE
[criticals] Context menu completely disappear

### ISSUE THREAD

**Issue by nhantrn** [choobin/cmis#25] opened 2013-01-21 04:39 UTC
I notice that after adding more items to a submenu, the context menu is gone when you go back to a page. Right clicking doesn't bring up the context menu after at all. You will need to restart Firefox to bring back the context menu.

Also, I notice that the experimental feature "Save links not just images" doesn't work. When I right click on a thumbnail to save the linked image, it saves the thumbnail instead of the linked image. You can test that out on this page http://www.autowp.ru/picture/eu3m7a

**Comment by choobin** [comment] 2013-01-21 05:43
> I notice that after adding more items to a submenu, the context menu is gone when you go back to a page. Right clicking doesn't bring up the context menu after at all. You will need to restart Firefox to bring back the context menu.

Crap! I can not seem to reproduce this. If possible could you please describe steps that might reproduce the error on my end. This will be a tremendous help. 

Also, could you check if there are any CMIS related error messages showing up in the error console.

To open the error console type: Ctrl - Shift - J

Or navigate from the Firefox button: Firefox -> Web Developer -> Error Console

The filter button in the bottom left could help here if you have loaded a page with lots of warnings/errors.

> Also, I notice that the experimental feature "Save links not just images" doesn't work. 

The old 'save links' coming back to bite me again. I have been having a lot of trouble with this feature, hence the experimental tag. Thanks for the heads up. I created a new issue for this so I do not forget about it again. [issue/26](https://github.com/choobin/cmis/issues/26).

**Comment by nhantrn** [comment] 2013-01-21 08:49
here's screen video of the of the bug http://temp-share.com/show/Pf3Yy3tc2

If I change anything in the menu items, it will produce that bug. From adding new items, deleting items, edit an item.

Now I though it could be interference with other ad-dons, but there's an bigger bug when I install this add-on on a clean profile of a firefox portable I keep to test stuff. When I install this addon on it, it wouldn't let me add anything at all.

Maybe I'm using a old version or the make.bat process is weird. Can you send me an xpi you made so I can test it?

**Comment by choobin** [comment] 2013-01-21 11:50
Wow. What a perfect method to describe the problem. Thank you for the video. 

This is concerning as I can not reproduce the issue. If you have time could you please send me bit more information and I will fix this asap.

First. 

What operating system are you using?

Is is a 32 or 64 bit version? 

What version of Firefox are you using? 

Do you have any other extensions installed that modify the context menu?

Second.

I need to know if there are any errors showing up in the Error Console. If this is the case it will tell me exactly where the issue is occurring. 

Open up to console (Ctrl-Shift-J) and perform and right click to open the context menu. If there is an issue with that component of the code it should tell us. Make sure to click the "All" or "Errors" button at the top of the console. Furthermore, check for any errors when performing other actions, for example, adding a new item in the settings (as it is not working).

Third. 

I need to know the contents of one of your CMIS preferences. 

In the URL bar could you type the following text and press enter.

about:config

If you have not done this before it will give you a warning message. Just click OK and continue.

I need to know to contents of the following value

`extensions.cmis@moongiraffe.net.directoryList`

Click on the entry and copy the contents (Ctrl-C).

> Maybe I'm using a old version or the make.bat process is weird. Can you send me an xpi you made so I can test it?

I am happy to send you an xpi when I make any changes. 

Is the make.bat file not working? I recently modified it to make it much easier to use. You should just need to click it and it will build and install (That is, if you have 7zip installed).

**Comment by KevinSanders** [comment] 2013-01-21 13:02
Hmm..I don't have this issue at all. I've got custom file formats, etc.

I've just enabled the save links (I personally don't use it), but it doesn't save any link in the same directory (or anywhere I can see).

Using the latest cmis-master.zip (20130119): 
MD5: DF032F7521D49DA8C9FC688C04B24356

Choobin, as a side-note, is it possible to name the zip file with a unique date/build? (or can we get an email notification when it's updated?), I know it's only temporary until you release it.

Windows 8 64-bit / Firefox 18.0.1
Tested on various random sites (including nhantrn's link in the original post). Cleared the error console before trying to download the image with CMIS (with save link on). 0 errors returned. 

But I don't see a link anywhere...Is it supposed to save a URL link in the same folder?

**Comment by nhantrn** [comment] 2013-01-22 01:52
First,
I'm using Firefox 19beta  on win7x32.

I have four add-ons that have its own menu item in the context menu. They are Launchy, Image Lookup, ABP, and Firebu

Second,
I forgot to mention in previous, but there were no errors message in the console

Third,
This is problematic, I removed CMIS. Now I reinstalled CMIS, but it won't let me add anything (which I mentioned in my earlier post). So no there's no data I can send you.

**Comment by choobin** [comment] 2013-01-23 05:58
@KevinSanders
@nhantrn

Thank you both for the information. This is really troubling. I have a very stringent test procedure across three operating systems and all version from 9.0 to the latest beta and have not encountered any of these issues. I am completely stumped.

If it is not adding anything in the menu it could be an issue with the directory list variable `extensions.cmis@moongiraffe.net.directoryList`. Could you delete the contents of this string and see if that solves the case.

**Comment by choobin** [comment] 2013-01-23 06:29
> Choobin, as a side-note, is it possible to name the zip file with a unique date/build? (or can we get an email notification when it's updated?), I know it's only temporary until you release it.

A good idea. [Here](https://github.com/choobin/cmis/tags) is a list of versions released on AMO since I put it up on github. From now on I will also tag and date stamp development versions, so refer to that page in the future when you want to download the latest release.

**Comment by choobin** [comment] 2013-01-26 12:16
@nhantrn Hi again. Just checking to see if the issue persisting? If you have the time, could you create a new profile and see if the newest build has the same issue. Regards, choobin

**Comment by choobin** [comment] 2013-01-29 13:54
Right. So I just encountered this bug. I traced it to the way the dialog was created. See [f13547749d](https://github.com/choobin/cmis/commit/f13547749d3335398cae9f1ac5b7abdc10ae578e). I will close this for now. However, if the issue remains please contact me.

**Closed as completed by choobin** 2013-01-29 13:54 UTC
Labels: bug

**Comment by nhantrn** [comment] 2013-01-30 00:38
Sry, for late reply. It seems you have fixed the issue. Awesome.
